# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 13:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=200)),
                ('lname', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('home_add', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Depart')),
            ],
        ),
    ]
